myapp/urls.py
from django.urls import path
from myapp import views

app_name = 'myapp'


urlpatterns = [
    path('register/', views.registration, name = 'register'),
    path('login/', views.user_login, name = 'login'),
] 

registration/urls.py
from django.contrib import admin
from django.urls import path, include
import myapp
from myapp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    path('', views.home, name='home'),
    path('logout/', views.user_logout, name='logout'),
    path('forgot-password/', views.forgot_password, name='forgot_pwd'),
    path('user-profile/', views.user_profile, name='profile'),
    path('change-password/', views.change_password, name='change_pwd'),


]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) # this is used only for getting images from url in browser

myapp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.TextField(max_length=200)
    profile_pic = models.ImageField(upload_to="profile_pic/")

    def __str__(self):
        return self.user.username
    

myapp/forms.py
from django import forms
from myapp.models import *

class UserForm(forms.ModelForm):
    password = forms.CharField(max_length=20, widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('address','profile_pic')

myapp/views.py
from django.shortcuts import render
from myapp.forms import *
from django.core.mail import send_mail

from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse


# Create your views here.


# User registration function
def registration(request):
    registered = False
    if request.method == "POST" and request.FILES:
        user_form = UserForm(request.POST)
        profile_form = ProfileForm(request.POST, request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user_form.cleaned_data['password'])
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            send_mail(
                'Registration Successfull',
                'Your registration is successfull, Thanks for registering',
                'arabindamahatojhantu@gmail.com', 
                [user.email],
                fail_silently=False,
            )
            registered = True
    user_form = UserForm()
    profile_form = ProfileForm()
    f = {'registered':registered,'user_form':user_form, 'profile_form':profile_form}
    return render(request, 'registration.html', context=f)



# User login function
def user_login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username = username, password = password)
        if user and user.is_active:
            login(request, user)
            request.session['username'] = username
            return HttpResponseRedirect(reverse('home'))
        else:
            return HttpResponse("Not an Active user or Invalid username or password")

    return render(request, 'login.html', context={})


# Getting User Name on HTML Page 
def home(request):
    if request.session.get('username'):
        user = request.session.get('username')
        return render(request, 'home.html', context={'username':user})
    return render(request, 'home.html')



@login_required 
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

def forgot_password(request):
    if request.method == "POST":
        username = request.POST['username']
        user = User.objects.get(username = username)
        if user:
            user.set_password("10101")
            send_mail(
                    'New Password',
                    'Your Password is reset successfully and your new password is \"10101\"',
                    'arabindamahatojhantu@gmail.com',
                    [user.email],
                    fail_silently=False,
                    )
            user.save()
        else:
            return HttpResponse("Invalid User")
    return render(request,'forgot_pwd.html')


@login_required
def user_profile(request):
        username = request.session['username']
        user = User.objects.get(username=username)
        # print(user.password)
        profile = Profile.objects.get(user=user)
        data = {'profile':profile}
        return render(request, 'profile.html',context=data)


@login_required
def change_password(request):
    username = request.session["username"]
    user = User.objects.get(username=username)
    if request.method == "POST":
        password = request.POST["newpassword"]
        user.set_password(password)
        user.save()
        HttpResponseRedirect(reverse('logout'))
    return render(request, 'change_pwd.html')


    


git init
git add .
git commit -m "first commit"
git remote add origin https://github.com/arabindamahato/LoginRegistration_CompleteProcess.git
git push -u origin master

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title %}
    <title>Home</title>
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    
</head>
<body>
    <!-- nav bar  -->
    <nav class="nav">
        <a class="nav-link" href="{% url 'home' %}">Home</a>
        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-link" href="{% url 'myapp:register' %}">Registration</a>         
        {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'logout' %}">logout</a>  
        <a class="nav-link" href="{% url 'profile' %}">Profile</a>  
        <a class="nav-link" href="{% url 'change_pwd' %}">Change Password</a>  
        {% else %}
        <a class="nav-link" href="{% url 'myapp:login' %}">Login</a>  
        {% endif %}       
    </nav>
    <!-- nav bar end  -->


    {% block body %}   
    <div class="container">
        <div class="jumbotron">
           Base
        </div>
    </div>
    {% endblock %}
    


</body>
</html>

templates/change_pwd.html
{% extends "base.html" %}

{% block title %}
<title>  Change Password
</title>
{% endblock %}

{% block body %}
  <div class="container">
      <div class="jumbotron">
        <form method="POST">
            {% csrf_token %}
            <label for="newpassword">New Password</label>
            <input type="password" name="newpassword" id="newpassword">
            <input type="submit" value="Change Password" class="btn btn-primary">
        </form>
      </div>
  </div>
{% endblock %}

templates/forgot_pwd.html
{% extends "base.html" %}
{% block title %}
  <title>Forgot Password</title>
{% endblock %}

{% block body %}
  <div class="container">
    <div class="jumbotron">
        <form method="POST">
            {% csrf_token %}
            <label for="username">Username :</label>
            <input type="text" name="username" id="username">
            <input type="submit" value="Send Mail" class="btn btn-primary">
        </form>
    </div>
  </div>
{% endblock %}

templates/home.html
{% extends "base.html" %}



{% block body %}
    <div class="container">
        {% if username %}
        <div class="jumbotron">
            <h1>Welcome Mr. / Mrs : {{username}}</h1>
           
        </div>
        {% else %}
        <div class="jumbotron">
            <h1>Welcome To Home Page</h1>
        </div>
        {% endif %}
        
        
    </div>
    {% endblock %}

    

templates/login.html
{% extends "base.html" %}

{% block title %}
    <title>Login</title>
{% endblock %}

{% block body %}
<div class="container">
    <div class="jumbotron">
        <form method="post">
            {% csrf_token %}
            <label for="username">Username :</label>
            <input type="text" name="username" id="username">
            <label for="password">Password :</label>
            <input type="password" name="password" id="password">
            <a href="{% url 'forgot_pwd' %}">Forgot Password ?</a>
            <input type="submit" value="Login" class="btn btn-primary">
        </form>
    </div>
</div>
{% endblock %}

templates/profile.html
{% extends "base.html" %}

{% block title %}
  <title>
      Profile
  </title>
{% endblock %}

{% block body %}
  <div class="container">
      <div class="jumbotron">
        <h3>Name : </h3> {{user.username}}
        <h3>Email : </h3> {{user.email}}
        <h3>Image : </h3> <img src="{{ profile.profile_pic.url }}" alt="Rohit's Image" height="100px" width="100px">
        
      </div>
  </div>
{% endblock %}

templates/registration.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Registration</title>
    {% endblock %}

{% block body %}
    <div class="container">
        {% if registered %}
        <div class="jumbotron">            
              <h1>Registration Successful</h1>            
        </div>

        {% else %}
        <div class="jumbotron">
           <center> <h2>Register Here</h2></center>
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{user_form|crispy}}
            {{profile_form|crispy}}
            <input type="submit" value="Register" class="btn btn-primary ">
          </form>
        </div>
    </div>
    {% endif %}
    {% endblock %}